### ISSUE TITLE
Could you provide a palette of darker hues? 

### ISSUE THREAD

**Issue by tzvine** [SprInec/typora-spring-theme#3]

**Comment by SprInec** [comment]
Hello🤗, I have added the dark theme of Spring to my schedule. Soon I will abstract the theme's color card in the `spring.css` file and make detailed comments and put it in the very beginning of `:root` so that everyone can modify it according to their preferences. 
At the same time, if you have any suggestions, requirements or ideas about the color palette, you can also tell me through issues. Your issues are very welcome😊.
